---
message: Hello World

spring:
    profiles: cloud
    application:
        name: ${vcap.application.application_name:atomicnumproducer}
    data:
        mongodb:
            database: first-atomic-number2
            username: example-user2
            password: example-password2
security:
  basic:
    enabled: false

management:
   security:
     enabled: false
